language: node_js
node_js: 
  - '6.3'

# S: Build Lifecycle
install:
  - npm install -g hexo
  - npm install -g hexo-cli
  - npm install
  - npm i hexo-generator-json-content --save


#before_script:
 # - npm install -g gulp

script:
  - hexo g

after_script:
  - cd ./public
  - git init
  - git config user.name "WJ Yang"
  - git config user.email "yangwj116@qq.com"
  - git add .
  - git commit -m "Update docs"
  - git push --force --quiet "https://${GH_TOKEN}@${GH_REF}" master:master
# E: Build LifeCycle

branches:
  only:
    - blog_source
env:
 global:
   - GH_REF: github.com/BitterPotato/BitterPotato.github.io